Repository CraterCrash/godot-orchestrator, pull requests merged in 2023-09, with the labels that each got.

#16 Fix more load order dependency failures
  addons/orchestrator/components/editor/node_tree_list.gd
  addons/orchestrator/components/editor/orchestration_graph.gd
  addons/orchestrator/orchestrator.gd
  addons/orchestrator/orchestrator_node_factory.gd
  addons/orchestrator/plugin.gd
  addons/orchestrator/views/main_view.gd
  addons/orchestrator/views/main_view.tscn
Labels: kind/bug

#14 added wait for action node
  addons/orchestrator/components/nodes/logic/wait_for_action_node.gd
Labels: kind/enhancement

#17 Document wait-for-input-action (#14)
  docs/modules/ROOT/assets/images/logic-node-wait-for-action.png
  docs/modules/ROOT/assets/images/logic-nodes.png
  docs/modules/ROOT/pages/nodes.adoc
Labels: kind/documentation
